In [ ]:
# Step1
import numpy as np
# Step2
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
# Step3
result = np.dot(A, B)
# Step4
print(result)
# Step5
print(result.max())

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
